# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Home
site_url: https://github.com/fralfaro/DS-Python-Course
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/DS-Python-Course
repo_url: https://github.com/fralfaro/DS-Python-Course
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/logo.bmp
  favicon: images/logo_python.svg
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/


# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - Home: index.md
    - Conceptos Básicos:
        - intro.ipynb
        - basic.ipynb
    - Manipulación Datos:
        - pandas.ipynb
        - seaborn.ipynb

